/**
 * TypeScript definitions for environment variables
 * Provides IntelliSense and type checking for process.env
 */

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      // ============================================
      // ADMIN PANEL (REQUIRED)
      // ============================================
      /**
       * Password for accessing the admin panel at /admin
       * Can be plain text (legacy) or bcrypt hash
       * Minimum 8 characters recommended
       * To hash: pnpm run hash-admin-password
       */
      ADMIN_PASSWORD: string;

      // ============================================
      // SITE CONFIGURATION (REQUIRED)
      // ============================================
      /**
       * Full URL of your site (no trailing slash)
       * Development: http://localhost:3000
       * Production: https://yourdomain.com
       */
      NEXT_PUBLIC_SITE_URL: string;

      // ============================================
      // JWT AUTHENTICATION (REQUIRED)
      // ============================================
      /**
       * Secret key for JWT token signing
       * MUST be at least 32 characters long
       * Generate with: openssl rand -base64 32
       * Keep this secret and never commit to version control
       */
      JWT_SECRET: string;

      // ============================================
      // SESSION CONFIGURATION (OPTIONAL)
      // ============================================
      /**
       * Session duration in seconds
       * Default: 604800 (7 days)
       * 1 day = 86400, 7 days = 604800, 30 days = 2592000
       */
      SESSION_DURATION?: string;

      // ============================================
      // VERCEL BLOB STORAGE (AUTO-CONFIGURED)
      // ============================================
      /**
       * Token for Vercel Blob Storage access
       * Auto-generated by Vercel in production
       * Leave empty for local development
       * DO NOT set manually - Vercel will handle this
       */
      BLOB_READ_WRITE_TOKEN?: string;

      // ============================================
      // VERCEL POSTGRES (OPTIONAL FOR DATABASE MODE)
      // ============================================
      /**
       * PostgreSQL database connection string (pooled)
       * Auto-generated by Vercel when you enable Postgres
       * For local development, use your local Postgres connection string
       * Format: postgres://user:password@host:port/database
       *
       * If not set, system falls back to legacy admin-only mode (no user auth)
       */
      POSTGRES_URL?: string;

      /**
       * PostgreSQL database connection string (non-pooled)
       * Used for direct connections in serverless functions
       * Auto-generated by Vercel when you enable Postgres
       */
      POSTGRES_URL_NON_POOLING?: string;

      // ============================================
      // VERCEL ENVIRONMENT
      // ============================================
      /**
       * Vercel environment identifier
       * Values: 'production' | 'preview' | 'development'
       */
      VERCEL_ENV?: 'production' | 'preview' | 'development';

      /**
       * Vercel deployment URL
       * Auto-generated by Vercel
       */
      VERCEL_URL?: string;

      // ============================================
      // NODE ENVIRONMENT
      // ============================================
      /**
       * Node.js environment
       * Values: 'production' | 'development' | 'test'
       */
      NODE_ENV: 'production' | 'development' | 'test';
    }
  }
}

// This export is required to make this a module
export {};
